#!/usr/bin/python3
import sys


def factorize_number(n):
    for i in range(2, n//2 + 1):
        if n % i == 0:
            print(f"{n}={n // i}*{i}")
            break


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    with open(input_file, 'r') as file:
        numbers = file.readlines()

    for number in numbers:
        n = int(number)
        factorize_number(n)
